### ISSUE TITLE
how to specify path or fileName to uploaded file 

### ISSUE THREAD

**Issue by dryhurst** [zaida04/multer-cloudflare-storage#1]
**I want to be able to specify a file path or filename**

its just uploading files like the image. 

<img width="661" alt="image" src="https://github.com/zaida04/multer-cloudflare-storage/assets/1443017/e8937824-26f3-487e-b5ee-f5b7f8ad8ea0">

shouldn't we be passing a filename to the .append method of the form data object? 

<img width="423" alt="image" src="https://github.com/zaida04/multer-cloudflare-storage/assets/1443017/d2544c73-c113-4a00-9831-c00cd96b53e3">

**Comment by zaida04** [comment]
Hey @dryhurst, thanks for the suggestion! I've released this feature in `1.1.0`.
You can install it using `npm install multer-cloudflare-storage@1.1.0`.

This will default the image name to whatever `file.originalname` is, which is typically whatever the name of your file is when you upload it to an express server using multer.

https://www.npmjs.com/package/multer-cloudflare-storage
